server:
  port: 8070

spring:
  application:
    name: eurekaserver

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false

    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    
